### ISSUE TITLE
python3 onnx_to_tensorrt.py  failed

### ISSUE THREAD

**Issue by Myron1996** [Stephenfang51/tracklite#22]
```
tdc@tdc:~/Downloads/tracklite$ python3 onnx_to_tensorrt.py --onnx ./weights/yolov3_416.onnx --output_engine ./weights/yolov3_416.engine
Loading ONNX file from path ./weights/yolov3_416.onnx...
Beginning ONNX file parsing
Completed parsing of ONNX file
Building an engine from file ./weights/yolov3_416.onnx; this may take a while...
[TensorRT] ERROR: Network must have at least one output
[TensorRT] ERROR: Network validation failed.
Completed creating Engine
Traceback (most recent call last):
  File "onnx_to_tensorrt.py", line 56, in <module>
    main()
  File "onnx_to_tensorrt.py", line 52, in main
    get_engine(args.onnx, args.output_engine)
  File "onnx_to_tensorrt.py", line 45, in get_engine
    f.write(engine.serialize())
AttributeError: 'NoneType' object has no attribute 'serialize'
```

Can you help please @Stephenfang51 . Thank you

**Comment by byq-luo** [comment]
我也是这个问题，求指导
