### ISSUE TITLE
Ran out of input when run run_tracker.py 

### ISSUE THREAD

**Issue by job2003** [Stephenfang51/tracklite#5]
nvidia@nvidia-desktop:~/tracklite$ python3 run_tracker.py --file --filename 2007-02.rm --output_file ./output.mp4
[rm @ 0x3eb64300] Invalid stream index 2 for index at pos 125670042
Traceback (most recent call last):
  File "run_tracker.py", line 107, in <module>
    main()
  File "run_tracker.py", line 88, in main
    tracker = Tracker(cfg, args.engine_path)
  File "/home/nvidia/tracklite/tracker/tracker.py", line 21, in __init__
    self.deepsort = build_tracker(cfg, use_cuda=True)
  File "/home/nvidia/tracklite/deep_sort/__init__.py", line 11, in build_tracker
    max_age=cfg.DEEPSORT.MAX_AGE, n_init=cfg.DEEPSORT.N_INIT, nn_budget=cfg.DEEPSORT.NN_BUDGET, use_cuda=use_cuda)
  File "/home/nvidia/tracklite/deep_sort/deep_sort.py", line 19, in __init__
    self.extractor = Extractor(model_path, use_cuda=use_cuda)
  File "/home/nvidia/tracklite/deep_sort/deep/feature_extractor.py", line 12, in __init__
    state_dict = torch.load(model_path, map_location=lambda storage, loc: storage)['net_dict']
  File "/home/nvidia/.local/lib/python3.6/site-packages/torch/serialization.py", line 385, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/nvidia/.local/lib/python3.6/site-packages/torch/serialization.py", line 562, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

when run python3 run_tracker.py --usb, same error. what's wrong?

**Comment by job2003** [comment]
any solution?
